#!/usr/bin/env python3
"""Deterministic helpers for reviewing Agent Skills.

The tool never executes code from the target skill. Data is written to stdout;
fatal diagnostics are written to stderr. Run this entry point with --help for
command-line usage.
"""

import os
import sys
from pathlib import Path

_PACKAGE_PARENT = str(Path(__file__).resolve().parent)
if not Path(_PACKAGE_PARENT, "skill_review", "__init__.py").is_file():
    sys.stderr.write(
        "Error: review_skill.py must run in place with its sibling "
        "skill_review package; that package is missing.\n"
    )
    raise SystemExit(2)
if _PACKAGE_PARENT not in sys.path:
    sys.path.insert(0, _PACKAGE_PARENT)

from skill_review.aggregate import (
    aggregate,
    metric,
    numeric,
    parse_run,
)
from skill_review.cli import (
    EXIT_CODES,
    add_output_options,
    build_parser,
    main,
    positive_int,
    write_result,
)
from skill_review.frontmatter import (
    TOP_KEY_RE,
    decode_scalar,
    has_unbalanced_flow_delimiters,
    parse_frontmatter,
)
from skill_review.fs_safety import (
    MAX_RESOURCE_DEPTH,
    MAX_RESOURCE_ENTRIES,
    MAX_TEXT_FILE_BYTES,
    MAX_TOTAL_TEXT_BYTES,
    READ_CHUNK_BYTES,
    WINDOWS_INVALID_FILENAME_RE,
    WINDOWS_REPARSE_POINT,
    WINDOWS_RESERVED_NAMES,
    InventoryIssue,
    InventoryState,
    TextReadBudget,
    TextReadError,
    file_type_name,
    first_link_like_component,
    is_link_like,
    is_reparse_stat,
    iter_files,
    read_bounded_regular_utf8,
    resolve_package_data_file,
    resolve_within,
    stable_file_signature,
    windows_filename_issue,
)
from skill_review.markdown_scan import (
    COMMONMARK_BACKSLASH_ESCAPE_RE,
    MARKDOWN_HTML_DECLARATION_START_RE,
    MARKDOWN_HTML_RAW_BLOCK_END_RES,
    MARKDOWN_HTML_RAW_BLOCK_START_RE,
    MARKDOWN_LIST_ITEM_RE,
    MARKDOWN_STANDALONE_BLOCK_RE,
    MAX_MARKDOWN_BRACKET_DEPTH,
    MAX_MARKDOWN_CODE_SPAN_DELIMITERS,
    MAX_MARKDOWN_CONTAINER_DEPTH,
    MAX_MARKDOWN_LINK_CANDIDATES,
    MAX_MARKDOWN_TARGET_CHARACTERS,
    NONLOCAL_TOKEN_RE,
    POWERSHELL_FENCE_LANGUAGES,
    RESOURCE_PATH_RE,
    SESSION_FENCE_LANGUAGES,
    SHELL_FENCE_LANGUAGES,
    SHELL_PROMPT_RE,
    SHELL_SCRIPT_CALL_RE,
    URI_SCHEME_IN_TOKEN_RE,
    URI_SCHEME_RE,
    MarkdownScanLimitError,
    _append_markdown_target,
    _markdown_blockquote_prefix,
    _markdown_html_block_ended,
    _markdown_html_block_terminator,
    _markdown_is_indented_code,
    _markdown_link_targets_on_line,
    _MarkdownLinkCandidate,
    _MarkdownScanBudget,
    _mask_markdown_block,
    _without_inline_code_in_block,
    backslash_escape_mask,
    commonmark_path,
    commonmark_unescape,
    extract_paths,
    markdown_link_target,
    markdown_link_targets,
    shell_script_path,
    split_markdown_fences,
    without_inline_code,
    without_nonlocal_tokens,
)
from skill_review.output import (
    aggregate_output_destination,
    output_dir_fd_supported,
    validate_output_entry,
    validate_output_entry_info,
    validate_output_parent,
    validate_output_root,
    write_aggregate_output,
    write_aggregate_output_with_dir_fd,
    write_aggregate_output_with_paths,
    write_output_descriptor,
)
from skill_review.report import (
    Finding,
    add_finding,
    finalize,
    line_number,
    render_text,
)
from skill_review.static_review import (
    INTERACTIVE_PATTERNS,
    NAME_RE,
    SCRIPT_SUFFIXES,
    add_text_read_error,
    first_actionable_match,
    script_help_detected,
    static_review,
)
from skill_review.validate_evals import (
    validate_evals,
)
from skill_review.validate_triggers import (
    TRIGGER_FIELDS,
    validate_triggers,
)

__all__ = [
    "COMMONMARK_BACKSLASH_ESCAPE_RE",
    "EXIT_CODES",
    "INTERACTIVE_PATTERNS",
    "MARKDOWN_HTML_DECLARATION_START_RE",
    "MARKDOWN_HTML_RAW_BLOCK_END_RES",
    "MARKDOWN_HTML_RAW_BLOCK_START_RE",
    "MARKDOWN_LIST_ITEM_RE",
    "MARKDOWN_STANDALONE_BLOCK_RE",
    "MAX_MARKDOWN_BRACKET_DEPTH",
    "MAX_MARKDOWN_CODE_SPAN_DELIMITERS",
    "MAX_MARKDOWN_CONTAINER_DEPTH",
    "MAX_MARKDOWN_LINK_CANDIDATES",
    "MAX_MARKDOWN_TARGET_CHARACTERS",
    "MAX_RESOURCE_DEPTH",
    "MAX_RESOURCE_ENTRIES",
    "MAX_TEXT_FILE_BYTES",
    "MAX_TOTAL_TEXT_BYTES",
    "NAME_RE",
    "NONLOCAL_TOKEN_RE",
    "POWERSHELL_FENCE_LANGUAGES",
    "READ_CHUNK_BYTES",
    "RESOURCE_PATH_RE",
    "SCRIPT_SUFFIXES",
    "SESSION_FENCE_LANGUAGES",
    "SHELL_FENCE_LANGUAGES",
    "SHELL_PROMPT_RE",
    "SHELL_SCRIPT_CALL_RE",
    "TOP_KEY_RE",
    "TRIGGER_FIELDS",
    "URI_SCHEME_IN_TOKEN_RE",
    "URI_SCHEME_RE",
    "WINDOWS_INVALID_FILENAME_RE",
    "WINDOWS_REPARSE_POINT",
    "WINDOWS_RESERVED_NAMES",
    "Finding",
    "InventoryIssue",
    "InventoryState",
    "MarkdownScanLimitError",
    "TextReadBudget",
    "TextReadError",
    "_MarkdownLinkCandidate",
    "_MarkdownScanBudget",
    "_append_markdown_target",
    "_markdown_blockquote_prefix",
    "_markdown_html_block_ended",
    "_markdown_html_block_terminator",
    "_markdown_is_indented_code",
    "_markdown_link_targets_on_line",
    "_mask_markdown_block",
    "_without_inline_code_in_block",
    "add_finding",
    "add_output_options",
    "add_text_read_error",
    "aggregate",
    "aggregate_output_destination",
    "backslash_escape_mask",
    "build_parser",
    "commonmark_path",
    "commonmark_unescape",
    "decode_scalar",
    "extract_paths",
    "file_type_name",
    "finalize",
    "first_actionable_match",
    "first_link_like_component",
    "has_unbalanced_flow_delimiters",
    "is_link_like",
    "is_reparse_stat",
    "iter_files",
    "line_number",
    "main",
    "markdown_link_target",
    "markdown_link_targets",
    "metric",
    "numeric",
    "os",
    "output_dir_fd_supported",
    "parse_frontmatter",
    "parse_run",
    "positive_int",
    "read_bounded_regular_utf8",
    "render_text",
    "resolve_package_data_file",
    "resolve_within",
    "script_help_detected",
    "shell_script_path",
    "split_markdown_fences",
    "stable_file_signature",
    "static_review",
    "validate_evals",
    "validate_output_entry",
    "validate_output_entry_info",
    "validate_output_parent",
    "validate_output_root",
    "validate_triggers",
    "windows_filename_issue",
    "without_inline_code",
    "without_nonlocal_tokens",
    "write_aggregate_output",
    "write_aggregate_output_with_dir_fd",
    "write_aggregate_output_with_paths",
    "write_output_descriptor",
    "write_result",
]

if __name__ == "__main__":
    raise SystemExit(main())
